/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorElegirMesa;
import controlador.VistaElegirMesa;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Jugador;
import modelo.Mesa;

/**
 *
 * @author feder
 */
public class ElegirMesa extends javax.swing.JDialog implements VistaElegirMesa {

    private ControladorElegirMesa controlador;
    private ArrayList<Mesa> mesas;
    /**
     * Creates new form ElegirMesa
     */
    public ElegirMesa(java.awt.Frame parent, boolean modal, Jugador j) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        initComponents();
        this.setTitle("Aplicación Jugador - Unirse a mesa");
        this.controlador = new ControladorElegirMesa(this,j);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listMesasAbiertas = new javax.swing.JList<>();
        bntUnirse = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        listMesasAbiertas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Mesas abiertas"));
        jScrollPane1.setViewportView(listMesasAbiertas);

        bntUnirse.setText("Unirse");
        bntUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntUnirseActionPerformed(evt);
            }
        });

        btnSalir.setText("Log off");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntUnirse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(72, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntUnirse)
                    .addComponent(btnSalir))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntUnirseActionPerformed
       unirseAMesa();
    }//GEN-LAST:event_bntUnirseActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       salir();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntUnirse;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listMesasAbiertas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void error(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void mostrarMesas(ArrayList<Mesa> mesas) {
        this.mesas = mesas;
        ArrayList<String> listado = new ArrayList();
        for(Mesa mesa: mesas){
            listado.add("Mesa #" + mesa.getNumMesa());
        }
        listMesasAbiertas.setListData(listado.toArray(new String[0]));
    }

    private void unirseAMesa() {
        Mesa m = mesas.get(listMesasAbiertas.getSelectedIndex());
        controlador.unirseAMesa(m);
    }
    
    public void proximoCasoUso(Jugador j, Mesa m) {        
        new JugarMesa(null, false, j, m).setVisible(true);
    }
    public void salir(){
        controlador.salir();
        this.dispose();
    }
    
}
