/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorIniciarMesa;
import controlador.VistaIniciarMesa;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import modelo.Croupier;
import modelo.TipoApuesta;

/**
 *
 * @author feder
 */
public class IniciarMesa extends javax.swing.JDialog implements VistaIniciarMesa{

    /**
     * Creates new form IniciarMesa
     */
    private ControladorIniciarMesa controlador;
    private ArrayList<TipoApuesta> tiposApuesta;
    
    public IniciarMesa(java.awt.Frame parent, boolean modal, Croupier c) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        initComponents();
        this.setTitle("Aplicación Croupier - Iniciar mesa");
        this.controlador = new ControladorIniciarMesa(this, c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarMesa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTiposApuesta = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnIniciarMesa.setText("Iniciar");
        btnIniciarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarMesaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listTiposApuesta);

        jLabel1.setText("Tipo de Apuesta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnIniciarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarMesaActionPerformed
        iniciarMesa();
    }//GEN-LAST:event_btnIniciarMesaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        salir();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listTiposApuesta;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarTiposApuesta(ArrayList<TipoApuesta> tiposDeApuesta) {
        this.tiposApuesta = tiposDeApuesta;
        ArrayList<String> listado = new ArrayList();
        for(TipoApuesta tp: tiposDeApuesta){
            listado.add(tp.getNombre());
        }
        listTiposApuesta.setListData(listado.toArray(new String[0]));
    }

    @Override
    public void iniciarMesa() {
        
        ArrayList<TipoApuesta> tp = new ArrayList();
        int[] v = listTiposApuesta.getSelectedIndices();
        for(int i: v){
            tp.add(this.tiposApuesta.get(i));
        }
        for(TipoApuesta tipo:tiposApuesta){
            if(tipo.isObligatorio()&& !tp.contains(tipo)){
                tp.add(tipo);
            }
        }
        controlador.IniciarMesa(tp);
        new OperarMesa(null,false,controlador.getElCroupier()).setVisible(true);
        this.setVisible(false);
    }

    private void salir() {
       controlador.logout();
    }
    
     

    
}
