/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import componente.PanelRuleta.Escuchador;
import controlador.ControladorJugarMesa;
import controlador.VistaJugarMesa;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Apuesta;
import modelo.Jugador;
import modelo.Mesa;

/**
 *
 * @author feder
 */
public class JugarMesa extends javax.swing.JDialog implements VistaJugarMesa, Escuchador {
    
    ControladorJugarMesa controlador;
    /**
     * Creates new form JugarMesa
     */
    public JugarMesa(java.awt.Frame parent, boolean modal, Jugador j, Mesa m) {
        super(parent, modal);
        initComponents();
        this.setTitle("Aplicación jugador");
        this.controlador = new ControladorJugarMesa(this, j, m);
        panelRuleta1.agregar(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelRuleta1 = new componente.PanelRuleta();
        lblSaldoJugador = new javax.swing.JLabel();
        lblDatosMesa = new javax.swing.JLabel();
        lblDatosPersonales = new javax.swing.JLabel();
        radioMoneda1 = new javax.swing.JRadioButton();
        radio5 = new javax.swing.JRadioButton();
        radio10 = new javax.swing.JRadioButton();
        radio50 = new javax.swing.JRadioButton();
        radio100 = new javax.swing.JRadioButton();
        lblUltimoGanador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosMesa = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOcurrencia = new javax.swing.JTable();
        btnSalirMesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonGroup1.add(radioMoneda1);
        radioMoneda1.setText("1");
        radioMoneda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMoneda1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio5);
        radio5.setText("5");

        buttonGroup1.add(radio10);
        radio10.setText("10");

        buttonGroup1.add(radio50);
        radio50.setText("50");

        buttonGroup1.add(radio100);
        radio100.setText("100");

        tblDatosMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ronda", "Total apostado", "Ganado", "Perdido", "Balance"
            }
        ));
        jScrollPane1.setViewportView(tblDatosMesa);

        tableOcurrencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor", "Ocurrencia"
            }
        ));
        jScrollPane2.setViewportView(tableOcurrencia);

        btnSalirMesa.setText("Abandonar");
        btnSalirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(radioMoneda1)
                        .addGap(18, 18, 18)
                        .addComponent(radio5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio100))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelRuleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUltimoGanador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSaldoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(lblDatosMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)
                                .addComponent(lblDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalirMesa)))
                        .addGap(0, 405, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSaldoJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDatosMesa, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblDatosPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMoneda1)
                    .addComponent(radio5)
                    .addComponent(radio10)
                    .addComponent(radio50)
                    .addComponent(radio100))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRuleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUltimoGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnSalirMesa)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMoneda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMoneda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMoneda1ActionPerformed

    private void btnSalirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMesaActionPerformed
        salirMesa();       
    }//GEN-LAST:event_btnSalirMesaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        salirMesa();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirMesa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatosMesa;
    private javax.swing.JLabel lblDatosPersonales;
    private javax.swing.JLabel lblSaldoJugador;
    private javax.swing.JLabel lblUltimoGanador;
    private componente.PanelRuleta panelRuleta1;
    private javax.swing.JRadioButton radio10;
    private javax.swing.JRadioButton radio100;
    private javax.swing.JRadioButton radio5;
    private javax.swing.JRadioButton radio50;
    private javax.swing.JRadioButton radioMoneda1;
    private javax.swing.JTable tableOcurrencia;
    private javax.swing.JTable tblDatosMesa;
    // End of variables declaration//GEN-END:variables

    @Override
    public void error(String msg) {
       JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void cargarNombreCompleto(String nombreCompleto) {
        lblDatosPersonales.setText(nombreCompleto);
    }

    @Override
    public void actualizarSaldo(double saldo) {
        lblSaldoJugador.setText(" $" + saldo);
    }

    @Override
    public void actualizarMesaRonda(int numMesa, int numeroRonda) {
        lblDatosMesa.setText("Ruleta #" + numMesa + " - Ronda #" + numeroRonda);
    }

    @Override
    public void celdaSeleccionada(int universalCellCode) {
        int ficha = getFichaSeleccionada();
       controlador.agrgarApuesta(universalCellCode, ficha);
    }

    private int getFichaSeleccionada() {
        int selectedItem = 0;
        if(radioMoneda1.isSelected()){
            selectedItem = 1;
        } else if(radio5.isSelected()){
            selectedItem = 5;
        } else if(radio10.isSelected()){
            selectedItem =10;
        } else if(radio50.isSelected()){
            selectedItem = 50;
        } else if(radio100.isSelected()){
            selectedItem = 100;
        }
        return selectedItem;
    }

    @Override
    public void mostrarApuestas(ArrayList<Apuesta> apuestas) {
        panelRuleta1.limpiar();
        for(Apuesta a: apuestas){
            panelRuleta1.setApuesta(a.getElCasillero().getUcc(), (int) a.getValor());            
        } 
    }

    private void salirMesa() {
       controlador.salir();
       
    }

    @Override
    public void mostrarValorOcurrencia(ArrayList<Integer> ocurrencia) {
       tableOcurrencia.removeAll();
       if(!ocurrencia.isEmpty()){
           mostrarUltimoNumero(ocurrencia.get(ocurrencia.size()-2)); 
       }
       
       
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Valor");
        datos.addColumn("Ocurrencia");
        
        
        
        int numColumnas = 2;
        int numFilas = ocurrencia.size() / numColumnas;
        datos.setRowCount(numFilas); 
        
       
        for (int fila = 0; fila < numFilas; fila++) {
        for (int columna = 0; columna < numColumnas; columna++) {
            int indice = fila * numColumnas + columna;
            if(columna == 1){
                datos.setValueAt(ocurrencia.get(indice) + " %", fila, columna);
            } else{
                datos.setValueAt(ocurrencia.get(indice), fila, columna);
            }            
            }
        }
        
        tableOcurrencia.setModel(datos);
    }

    @Override
    public void limpiar() {
        panelRuleta1.limpiar();
    }

    private void mostrarUltimoNumero(int ultimoGanador) {
        lblUltimoGanador.setText("Ultimo numero ganador: " + ultimoGanador + "");
    }

    @Override
    public void mostrarEstadisticasjugador(ArrayList<String> estadisticas) {
        tblDatosMesa.removeAll();       
       
       
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Ronda");
        datos.addColumn("Total Apostado");
        datos.addColumn("Ganado");
        datos.addColumn("Perdido");
        datos.addColumn("Balance");
        
        
        
        int numColumnas = 5;
        int numFilas = estadisticas.size() / numColumnas;
        datos.setRowCount(numFilas); 
        
       
        for (int fila = 0; fila < numFilas; fila++) {
        for (int columna = 0; columna < numColumnas; columna++) {
            int indice = fila * numColumnas + columna;
            
                datos.setValueAt(estadisticas.get(indice), fila, columna);
                        
            }
        }
        
        tblDatosMesa.setModel(datos);
    }

    @Override
    public void cerrar() {
        this.dispose();
    }

    @Override
    public void cerroMesa(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Cerro la Mesa", JOptionPane.ERROR_MESSAGE);
        cerrar();
    }    
}
