/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import componente.PanelRuleta.Escuchador;
import controlador.ControladorOperarMesa;
import controlador.VistaOperarMesa;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Apuesta;
import modelo.Casillero;
import modelo.Croupier;
import modelo.Efecto;
import modelo.Jugador;
import modelo.Ronda;


public class OperarMesa extends javax.swing.JDialog implements VistaOperarMesa,Escuchador{

    private ControladorOperarMesa controlador;
   
    public OperarMesa(java.awt.Frame parent, boolean modal, Croupier c) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        initComponents();
        this.setTitle("Aplicación Croupier - Operar ruleta");
        this.controlador = new ControladorOperarMesa(this, c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelRuleta1 = new componente.PanelRuleta();
        lblBalanceMesa = new javax.swing.JLabel();
        lblRonda = new javax.swing.JLabel();
        lblNumRuleta = new javax.swing.JLabel();
        btnCerrarMesa = new javax.swing.JButton();
        lblDatosRonda = new javax.swing.JLabel();
        btnLanzarPagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUltimosLanzamientos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDatosMesa = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblJugadores = new javax.swing.JTable();
        lblUltimoNumero = new javax.swing.JLabel();
        comboEfectos = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnCerrarMesa.setText("Cerrar Mesa");
        btnCerrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarMesaActionPerformed(evt);
            }
        });

        btnLanzarPagar.setText("Lanzar/Pagar");
        btnLanzarPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarPagarActionPerformed(evt);
            }
        });

        tblDatosMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ronda", "Balance anterior", "Apuestas", "Recolección", "Liquidación", "Balance posterior"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDatosMesa);

        tblJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jugador", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblJugadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelRuleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblUltimosLanzamientos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(lblDatosRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboEfectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)
                            .addComponent(btnLanzarPagar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblBalanceMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(173, 173, 173)
                            .addComponent(lblRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(206, 206, 206)
                            .addComponent(lblNumRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUltimoNumero)
                    .addComponent(btnCerrarMesa))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalanceMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnCerrarMesa))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumRuleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatosRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLanzarPagar)
                    .addComponent(comboEfectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelRuleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblUltimoNumero)))
                .addGap(12, 12, 12)
                .addComponent(lblUltimosLanzamientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(304, 304, 304))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void btnLanzarPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarPagarActionPerformed
        lanzarPagar(false);
    }//GEN-LAST:event_btnLanzarPagarActionPerformed

    private void btnCerrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarMesaActionPerformed
        lanzarPagar(true);
    }//GEN-LAST:event_btnCerrarMesaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       lanzarPagar(true);
    }//GEN-LAST:event_formWindowClosing

    //Este salir no lo estoy utilizando
    private void salir() {
        controlador.salir();
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarMesa;
    private javax.swing.JButton btnLanzarPagar;
    private javax.swing.JComboBox comboEfectos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBalanceMesa;
    private javax.swing.JLabel lblDatosRonda;
    private javax.swing.JLabel lblNumRuleta;
    private javax.swing.JLabel lblRonda;
    private javax.swing.JLabel lblUltimoNumero;
    private javax.swing.JLabel lblUltimosLanzamientos;
    private componente.PanelRuleta panelRuleta1;
    private javax.swing.JTable tblDatosMesa;
    private javax.swing.JTable tblJugadores;
    // End of variables declaration//GEN-END:variables

    @Override
    public void celdaSeleccionada(int universalCellCode) {
        //Es necesario para el caso del Croupier?
    }
    
    
    @Override
    public void cargarEfectos(ArrayList<Efecto> efectos) {
        for(Efecto e: efectos){
            comboEfectos.addItem(e);
        }
    }

    @Override
    public void actualizarBalance(double Balance) {
        lblBalanceMesa.setText(" $" + Balance);
    }

    @Override
    public void actualizarRonda(int numRonda) {
        lblRonda.setText("Ronda # " + numRonda);
    }

    @Override
    public void actualizarUltimosNumeros(ArrayList<Integer> sorteados) {
        String text = "Últimos lanzamientos: ";
        for(int i: sorteados){
            text = text + i + ", ";
        }
        
        lblUltimosLanzamientos.setText(text);
        lblUltimoNumero.setText(" Ultimo numero: " + sorteados.get(0));
    }

    @Override
    public void actualizarJugadores(ArrayList<Jugador> jugadores) {
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Jugador");
        datos.addColumn("Saldo");       
        
        datos.setRowCount(jugadores.size());
        int fila = 0;        
        
        for(Jugador j: jugadores){
            datos.setValueAt(j.getNombreCompleto(), fila, 0);
            datos.setValueAt(j.getSaldo(), fila, 1);
            fila++;            
        }
        tblJugadores.setModel(datos);
    }

    @Override
    public void cargarNumRuleta(int num) {
        lblNumRuleta.setText("Ruleta # " + num);
    }

    @Override
    public void actualizarTablaRondas(ArrayList<String> recibidos) {
       tblDatosMesa.removeAll();
        
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Ronda");
        datos.addColumn("Balance anterior");
        datos.addColumn("Apuestas");
        datos.addColumn("Recolección");
        datos.addColumn("Liquidación");
        datos.addColumn("Balance posterior");
        
        
        int numColumnas = 6;
        int numFilas = recibidos.size() / numColumnas;
        datos.setRowCount(numFilas); 
        
       /* for(int i = 0; i < recibidos.size(); i++ ){
            datos.setValueAt(recibidos.get(i), fila, i - (fila*6));
            if(i+1%6 == 0)fila++;
        }*/
        for (int fila = 0; fila < numFilas; fila++) {
        for (int columna = 0; columna < numColumnas; columna++) {
            int indice = fila * numColumnas + columna;
            datos.setValueAt(recibidos.get(indice), fila, columna);
            }
        }
        
        tblDatosMesa.setModel(datos);
    }

    @Override
    public void actualizarRondaActual(int apuestas, double monto) {
        lblDatosRonda.setText("Apuestas: " + apuestas + "| Monto: $" + monto);
    }

    private void lanzarPagar(boolean salir) {
        Object seleccionado = comboEfectos.getItemAt(comboEfectos.getSelectedIndex());
        Efecto efecto = (Efecto) seleccionado;
        controlador.lanzarPagar(efecto, salir);
        if(salir)this.dispose();
    }

    @Override
    public void actualizarUltimoNumero(int numeroGanador) {
        lblUltimoNumero.setText(" Ultimo numero: " + numeroGanador);
    }

    @Override
    public void mostrarApuestas(ArrayList<Casillero> casilleros) {
        for(Casillero c: casilleros){
            panelRuleta1.setApuesta(c.getUcc(), (int) c.getTotalApostado());            
        } 
    }
    public void mostrarOcultarCasilleros(ArrayList<Casillero> casilleros){
        panelRuleta1.setVisible( false);
        for(Casillero c: casilleros){
            panelRuleta1.setVisible( c.getUcc(), true);
        }
    }





}
